### ISSUE TITLE
Parameter NOBEEP

### ISSUE THREAD

**Issue by ricardocarrer** [zaf/asterisk-speech-recog#16]
Hi! 

The fourth parameter is not read, independent parameter passed or not.

Congratulations for the work.

at,
Carrer

**Comment by zaf** [comment]
I don't seem to be able to reproduce this here. When using something like:
agi(speech-recog.agi,en-US,,,NOBEEP)
no beep sound is played when the recording starts.
Are you using the latest version of the script from the git repo?

**Comment by ricardocarrer** [comment]
Downloaded the API again and it worked. Probably I was going quoted and
ended up changing the original acted and ruining something.

Sorry!




From:  Lefteris Zafiris <notifications@github.com>
Reply-To:  zaf/asterisk-speech-recog
<reply+0081f4d49c9a54ebf52625d825cba5b46397b3498675c6e892cf0000000110e3a0bc9
2a169ce03578045@reply.github.com>
Date:  sexta-feira, 30 de janeiro de 2015 17:42
To:  zaf/asterisk-speech-recog <asterisk-speech-recog@noreply.github.com>
Cc:  Ricardo Carrer <ricardocarrer@gmail.com>
Subject:  Re: [asterisk-speech-recog] Parameter NOBEEP (#16)


I don't seem to be able to reproduce this here. When using something like:
agi(speech-recog.agi,en-US,,,NOBEEP)
no beep sound is played when the recording starts.
Are you using the latest version of the script from the git repo?

‹
Reply to this email directly or view it on GitHub
<https://github.com/zaf/asterisk-speech-recog/issues/16#issuecomment-7225843
2> .
