### ISSUE TITLE
Cloud Speech API BETA 

### ISSUE THREAD

**Issue by poing** [zaf/asterisk-speech-recog#28]
Has any work been done towards using the NEW Cloud Speech API?
https://cloud.google.com/speech/

I didn't have any luck with changing the host:
https://speech.googleapis.com/v1beta1/speech:syncrecognize

**Comment by zaf** [comment]
I didn't find any time to work on this yet.

**Comment by poing** [comment]
I did some testing with the Google [python samples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/api).  Successfully passing µ-law files via CLI. 


```diff
--- speech_rest.py	(revision 816)
+++ speech_rest.py	(working copy)
@@ -62,8 +62,8 @@
             'config': {
                 # There are a bunch of config options you can specify. See
                 # https://goo.gl/EPjAup for the full list.
-                'encoding': 'LINEAR16',  # raw 16-bit signed LE samples
-                'sampleRate': 16000,  # 16 khz            
+                'encoding': 'MULAW',  # G.711 PCMU/mu-law
+                'sampleRate': 8000,  # 8 khz           
``` 
`export GOOGLE_APPLICATION_CREDENTIALS=/google_speech_api.json`
`python speech_rest.py /var/lib/asterisk/sounds/en/hello.ulaw `

```json
{"results": [{"alternatives": [{"confidence": 0.97280418999999996, "transcript": "hello"}]}]}
```

 It's a step closer to working AGI script.  But have not had much time to work on it either.

**Comment by poing** [comment]
Uploaded working code, written in python.  Do with it as you like.

**Comment by jaylabade** [comment]
Hi,

Can you please provide code for PHP/Python
