### ISSUE TITLE
Unable to get recognition data

### ISSUE THREAD

**Issue by gabrielBarbutti** [zaf/asterisk-speech-recog#32]
I get the error "Unable to get recognition data" and the two variables are set to -1. I know that this means my connection to google was not sucessful, but I tested with this command (curl -X POST --data-binary @'/var/lib/asterisk/sounds/en/hello-world.wav' --header 'Content-Type: audio/l16; rate=8000;' 'https://www.google.com/speech-api/v2/recognize?output=json&lang=en-us&key=*******') and the connection was sucessful. 
Here is my CLI output:
![imagem1](https://cloud.githubusercontent.com/assets/18507750/20215065/28c70bda-a7f9-11e6-9f5d-e297e9245dd7.png)

**Comment by dhawangupta** [comment]
Hi, were you able to make it work??
Is Google Speech API still available?
I tried sending an HTTP POST request (https://www.google.com/speech-api/v2/recognize?output=json&lang=en-us&key=<API-Key>&client=chromium&maxresults=6&pfilter=2) via Postman and got an empty json:
{
  "result": []
}

**Comment by aidoskz** [comment]
Hi @dhawangupta i think it is old style
new style of Google Speech Api
 
POST /v1beta1/speech:syncrecognize?fields=results&key=<YOUR_API_KEY>
HTTP/1.1
HOST: speech.googleapis.com
content-type: application/json
content-length: 37278

{
  "config": {
    "encoding": "FLAC",
    "sampleRate": 8000,
    "languageCode": "ru-RU"
  },
  "audio": {
    "content": "<base64encodedFile>"
  }
}
 
More information : [https://cloud.google.com/speech/reference/rest/](https://cloud.google.com/speech/reference/rest/)

**Comment by dhawangupta** [comment]
Yes @aidoskz  you are right. This is new Google Cloud Speech API which needs to enable billing in the Google Cloud Console too.

**Comment by zaf** [comment]
There is a version for the new cloud API, its under the 'cloud_api' branch. As far as I know both APIs work at the moment.

**Comment by dhawangupta** [comment]
Hi @zaf, but, the older API only returns
{
"result": []
}
