### ISSUE TITLE
Unable to get recognition data

### ISSUE THREAD

**Issue by richard24se** [zaf/asterisk-speech-recog#33]
Hello Zaf,
I use asterisk 1.4, Centos 6.5 and have update lib requeriments. I trye everything and debug code, but always appers that:
[Nov 24 00:25:26] NOTICE[38776]: rtp.c:1287 ast_rtp_read: Unknown RTP codec 95 received from '190.113.208.170'
AGI Rx << SET VARIABLE "utterance" "-1"
AGI Tx >> 200 result=1
AGI Rx << SET VARIABLE "confidence" "-1"
AGI Tx >> 200 result=1
AGI Rx << CHANNEL STATUS
AGI Tx >> 200 result=6
AGI Rx << GET FULL VARIABLE ${CHANNEL(audionativeformat)}
AGI Tx >> 200 result=1 (ulaw)
AGI Rx << RECORD FILE /tmp/stt_kxT7jG sln  "#" "-1" BEEP "s=2"
    -- <SIP/81-54014f50> Playing 'beep' (language 'en')
AGI Tx >> 200 result=35 (dtmf) endpos=25440
AGI Rx << VERBOSE "Unable to get recognition data." 3

Can u help me please.

**Comment by spicyramen** [comment]
+1

**Comment by warenbe** [comment]
This problem is due to missing perl packages
on my centos i was forced to do: 

yum install perl-LWP-Protocol-https perl-Crypt-SSLeay perl-JSON perl perl-libwww
the first 2 packages were missing.

after that, it works fine.
i suppose, if you cannot install packages, that you can just remove the hostname check off by putting 
verify_hostname => 0 instead of verify_hostname => 1

**Comment by zeeshankareem** [comment]
@warenbe I am facing an issue in speech recognition, Can you please let me know If I  have to use my own google speech API Key?

Thanks

**Comment by warenbe** [comment]
yes you have to put your own api key.

**Comment by zeeshankareem** [comment]
@warenbe  Thanks for your reply


Now I am getting this error

 VERBOSE "Unable to get recognition data." 3
    -- asterisk-speech-recog/speech-recog.agi,en-US: Unable to get recognition data.

What can be the issue?

Thanks in advance

**Comment by obiebrown** [comment]
I believe script "maybe working" but I now get.
Script returned:  ,
As in it is not returning any {utterance} or {confidence}
I had issue and used "warenbe" solution to fix "missing perl packages" before doing this I was getting a -1, and -1 return as if it was error. So I believe script had issues, yet now it is returning nothing once fixing this. Can it be some other missing package that is causing this or what would you suggest I try?

Any help would be great :)

**Comment by YashMistry3120** [comment]
> This problem is due to missing perl packages
> on my centos i was forced to do:
> 
> yum install perl-LWP-Protocol-https perl-Crypt-SSLeay perl-JSON perl perl-libwww
> the first 2 packages were missing.
> 
> after that, it works fine.
> i suppose, if you cannot install packages, that you can just remove the hostname check off by putting
> verify_hostname => 0 instead of verify_hostname => 1



> This problem is due to missing perl packages
> on my centos i was forced to do:
> 
> yum install perl-LWP-Protocol-https perl-Crypt-SSLeay perl-JSON perl perl-libwww
> the first 2 packages were missing.
> 
> after that, it works fine.
> i suppose, if you cannot install packages, that you can just remove the hostname check off by putting
> verify_hostname => 0 instead of verify_hostname => 1

What is a command for debain?
