### ISSUE TITLE
Problems whit google API credencials

### ISSUE THREAD

**Issue by TheMasterRoot** [zaf/asterisk-speech-recog#35]
Hello im using your agi into my asterisk but im getting a error on apikey
i generated it on my google developer panel but it says that i dont have permission to use that key
please could you help me to generate a valid one?

**Comment by inaciose** [comment]
Same here

**Comment by velegip** [comment]
+1 @zaf

**Comment by zaf** [comment]
I can't really replicate this issue, as far as the API is concerned the scripts are working as supposed to.
What is the exact error in this case?

**Comment by abesherman** [comment]
what happens when u put this in your terminal console? curl https://speech.googleapis.com/v1beta1/speech:syncrecognize?key=_Your_ API_Key_Here   -X POST -d '{}'
