### ISSUE TITLE
still working up to now?

### ISSUE THREAD

**Issue by emmanuelrey2017** [zaf/asterisk-speech-recog#37]
thank you.

**Comment by AlphaBootis** [comment]
Seems to be working here.

**Comment by capouch** [comment]
I hope I could ask for a little help.  I am running Asterisk 14.6.0 on Centos 7.1, have installed (using yum) the various Perl packages, and am getting the "speech-recog.agi,en-US: Unable to get recognition data." error mentioned in Issue #33.  

Using this page [https://cloud.google.com/speech/docs/getting-started](url) I am able to call the API just fine.

The Google Apps dashboard reports that the system is returning Error 400 on the requests I am making from Asterisk.

I know this isn't a support forum, but if anyone seeing this could give me a pointer, I'd be much obliged.
