### ISSUE TITLE
Unable to get recognition data

### ISSUE THREAD

**Issue by zeeshankareem** [zaf/asterisk-speech-recog#41]
Hello Zaf,

Hope you are doing great.

 I am getting this error

VERBOSE "Unable to get recognition data." 3
-- asterisk-speech-recog/speech-recog.agi,en-US: Unable to get recognition data.

What can be the issue?

Thanks in advance

**Comment by ernany** [comment]
I'm too

**Comment by wsotest** [comment]
Me too

**Comment by 26tajeen** [comment]
What was the fix for this?
