### ISSUE TITLE
Output from Google.

### ISSUE THREAD

**Issue by amyraemcmahon** [zaf/asterisk-speech-recog#42]
I found that adding a lc (${utterance}); works great great in the perl script. I find that google sometimes Capitalizes things and sometimes not. So if your using a [mainmenu] goto(${utterance},1) command in your dialplan sometimes you need Two of the same otherwise, Like sales & Sales. Adding a LC to the variable from output can change all that. 

I hope this script has additions to it to show alternative values. Like sometimes my customers word comes back as play instead of clay. If I could run a script to find alternative words returned and match it with words from a list it would be much better and functional. 

If anyone has went further with this script such as above please help!

**Comment by zaf** [comment]
Have a look at this example:
https://github.com/zaf/asterisk-speech-recog/blob/master/cli/replace.agi
