### ISSUE TITLE
variable silence

### ISSUE THREAD

**Issue by ramin-git** [zaf/asterisk-speech-recog#46]
Hi.
I can not find where and how is using $silence.

**Comment by zaf** [comment]
$silence is passed as parameter to 'RECORD FILE' AGI command to set the
number of seconds of silence allowed before the function returns despite the
lack of dtmf digits or reaching timeout.
https://wiki.asterisk.org/wiki/display/AST/AGICommand_RECORD+FILE

You can see that in the AGI script in line 190
