### ISSUE TITLE
Sln file availability after recording

### ISSUE THREAD

**Issue by mirkpul** [zaf/asterisk-speech-recog#47]
Using Asterisk version 13.17 on ubuntu 17.10 the file sln takes time to be persisted. So then flac conversion fails with 256 error code returned (file does not exist).

There could be a parallel process running on asterisk saving  the sln files. If I add a sleep before converting the file it works.

Wondering if it would be better to check the file presence and if it's locked.

**Comment by zaf** [comment]
Do you, by any chance, have the parameter 'cache_record_files' set to 'yes' in your asterisk.conf?

**Comment by mirkpul** [comment]
No, it's commented out:

;cache_record_files = yes ; Cache recorded sound files to another

Any other idea?

Mirko

Il giorno ven 23 feb 2018 alle ore 22:21 Lefteris Zafiris <
notifications@github.com> ha scritto:

**Comment by zaf** [comment]
The only similar problem I have come across is with `cache_record_files` enabled in some small systems like raspberry pi. In these cases the file was empty, syncing to disk was taking time.
I can't say I have seen the behaviour you describe before.

**Comment by mirkpul** [comment]
It's a virtual machine on vmware Player..do you think this could be the
problem?

Mirko

Il 26 Feb 2018 11:49 AM, "Lefteris Zafiris" <notifications@github.com> ha
scritto:
