### ISSUE TITLE
I think google's speech recognition API changed

### ISSUE THREAD

**Issue by issackelly** [zaf/asterisk-speech-recog#9]
My calls aren't currently processing, This might be the culprit.

http://www.reddit.com/r/raspberry_pi/comments/251yur/google_speech_api_has_changed/

**Comment by raciel88** [comment]
dvarella, a lot of thanks, you solved a lot of problems that I had, :-) Greetings from México.!

**Comment by dvarella** [comment]
You're welcome !

   Cheers !

--

Daniel Varella de Oliveira
Consultor de T.I.
Cel.: +55(21)98615-6050

Digium Certified Asterisk Professional - (dCAP)

Novell Certified Linux Administrator (Novell CLA) &
Novell Data Center Technical Specialist (Novell DCTS)
SUSE Linux Enterprise 11

Linux Professional Certified - LPI

Information Technology Infrastructure Library - ITIL Certified

Cisco Certified Network Associate - CCNA

**Comment by raciel88** [comment]
I need help.! When I execute this program with Python 2.7:

import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:                # use the default microphone as the audio source
    audio = r.listen(source)                   # listen for the first phrase and extract it into audio data

try:
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
except LookupError:                            # speech is unintelligible
    print("Could not understand audio")

I receive the next errors:

File "web1.py", line 4, in <module>
	audio = r.listen(source)   #listen for the first phrase and extract it into audio data

File "/usr/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 268, in listen
	buffer = source.stream.read(source.CHUNK)

File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 605, in read
	return pa.read_stream(self._stram, num_frames)

keyboardInterrupt

Or somebody has a program that works fine using the web speech API,

Please help.!
